version: '3'

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    restart: always
    networks:
      - inception-net

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    build: ./requirements/wordpress
    volumes:
      - wp-data:/var/www/html
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_DB_NAME: ${MYSQL_DATABASE}
      WP_DB_USER: ${MYSQL_USER}
      WP_DB_PASSWORD: ${MYSQL_PASSWORD}
      WP_DB_HOST: ${WP_DB_HOST}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      ANOTHER_USER: ${ANOTHER_USER}
      ANOTHER_EMAIL: ${ANOTHER_EMAIL}
      ANOTHER_PASSWORD: ${ANOTHER_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
    restart: always
    networks:
      - inception-net

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx
    volumes:
      - wp-data:/var/www/html
    ports:
      - '443:443'
    restart: always
    networks:
      - inception-net

  redis:
    container_name: redis
      #    depends_on:
      #      - wordpress
    build: ./requirements/bonus/redis
    ports:
      - '6379:6379'
    restart: always
    networks:
      - inception-net

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp
    volumes:
      - wp-data:/var/www/html
    ports:
      - '20:20'
      - '21:21'
      - '10000-10100:10000-10100'
    environment:
      FTP_USER: ${FTP_USER}
      FTP_PASSWORD: ${FTP_PASSWORD}
    restart: always
    networks:
      - inception-net

  adminer:
    container_name: adminer
    depends_on:
      - mariadb
    build: ./requirements/bonus/adminer
    ports:
      - '8080:8080'
    restart: always
    networks:
      - inception-net

networks:
  inception-net:

volumes:
  wp-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/prrattan/data/wordpress

  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/prrattan/data/mariadb
